name: "Release: Publish"

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/patch'
      - 'release/minor'
jobs:
  publish-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4